title:              "Have been Marketing"
tagline:            "합니의 백수탈출 대작전"
email:              "habnipark@gmail.com"
description:        "부르주아를 꿈꾸는 백수의 백수탈출기"
author:             "Habni"
baseurl:            "/"
url:                "https://have-been.com"
locale:             "en_us"
thumbnail:          "/img/thumbnail.png"



# Social Profiles
instagram_username:
facebook_username:
linkedin_username:

# Build settings
markdown:           kramdown
permalink:          /:title
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

# 블로그 disqus shortname
disqus:
  shortname: have-been-marketing
